### ISSUE TITLE
bug: cannot visualize the volume resources defined in service block.

### ISSUE THREAD

**Issue by wf-yamaday** [wf-yamaday/yaml-visualizer#1]
## what problem ?

If the volume resources defined in service block as the same path as another service, cannot visualize both resources.

This sample here.

```yaml
version: '3.7'

services:

  master:
    container_name: mysql_master
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./master/conf/:/conf
      - ./setup.sh:/usr/local/bin/setup.sh
      - master_log/:/var/log/mysql/
      - master_db:/var/lib/mysql

  slave:
    container_name: mysql_slave
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./slave/conf/:/conf
      - ./setup.sh:/usr/local/bin/setup.sh
      - slave_log/:/var/log/mysql/
      - slave_db:/var/lib/mysql
```

![image](https://user-images.githubusercontent.com/27722351/124483542-6bc11f80-dde5-11eb-9924-303b86d4daf1.png)
